### ISSUE TITLE
ResourceExhaustedError：Out of memory error on GPU 0.

### ISSUE THREAD

**Issue by Firework471** [PaddlePaddle/ERNIE#479]
错误信息：
RuntimeError: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
Windows not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 25.000244MB memory on GPU 0, available memory is only 2.349999MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please try one of the following suggestions:
   1) Decrease the batch size of your model.
   2) FLAGS_fraction_of_gpu_memory_to_use is 0.50 now, please set it to a higher value but less than 1.0.
      The command is `export FLAGS_fraction_of_gpu_memory_to_use=xxx`.

 at (D:\1.7.1\paddle\paddle\fluid\memory\detail\system_allocator.cc:150)

部分代码（基本是按照教程写的）：
    for j in range(len(train_data) // BATCH):
        feature, label = get_batch_data(train_data, j)
        loss, _ = ernie(feature, labels=label) # ernie模型的返回值包含(loss, logits)；其中logits目前暂时不需要使用
        loss.backward()
        optimizer.minimize(loss)
        ernie.clear_gradients()
        if j % 10 == 0:
            print('train %d: loss %.5f' % (j, loss.numpy()))
        # evaluate
        if j % 100 == 0:
            all_pred, all_label = [], []
            with D.base._switch_tracer_mode_guard_(is_train=False): # 在这个with域内ernie不会进行梯度计算；
                ernie.eval() # 控制模型进入eval模式，这将会关闭所有的dropout；
                for j in range(len(test_data) // BATCH):
                    feature, label = get_batch_data(test_data, j)
                    loss, logits = ernie(feature, labels=label)
                    all_pred.extend(L.argmax(logits, -1).numpy())
                    all_label.extend(label.numpy())
                ernie.train()
            f1 = f1_score(all_label, all_pred, average='macro')
            acc = (np.array(all_label) == np.array(all_pred)).astype(np.float32).mean()
            print('acc %.5f' % acc)
调试的啥时候出错的地方是loss, _ = ernie(feature, labels=label) 这一行
在代码前面加了
os.environ['FLAGS_fraction_of_gpu_memory_to_use'] = "0.9"
os.environ["FLAGS_eager_delete_tensor_gb"] = "0"
并且把batch调成1依然还是出现同样的错误，希望各位大佬不吝赐教，感激感激！

**Comment by oyxuan-11** [comment]
给出几个建议
1. 试着调小一点max_seq_len
2. 请问显存大小是多少呢，如果不够的话可以放在AI Studio上运行，显存16G
3. 试着跑一下ernie 自带的例程脚本，排查一下是机器问题还是代码问题

**Comment by Firework471** [comment]
> 给出几个建议
> 
> 1. 试着调小一点max_seq_len
> 2. 请问显存大小是多少呢，如果不够的话可以放在AI Studio上运行，显存16G
> 3. 试着跑一下ernie 自带的例程脚本，排查一下是机器问题还是代码问题

谢谢您的建议，我的显存是8G，目前来看不像是显存大小问题，因为当我不管是调小batch size还是max_seq_len的时候，都会出现这个错误，并且“Out of memory error on GPU 0. Cannot allocate 25.000244MB memory on GPU 0, available memory is only 2.349999MB.”这段话中的那两个数值会随着batch size和max_seq_len的减小而减小，但始终是Out of memory error。之前有相同问题的issue中提到可以通过设置FLAGS_fraction_of_gpu_memory_to_use等方法来解决，但是目前看来对于我的程序似乎是不起作用的。

**Comment by Firework471** [comment]
> 给出几个建议
> 
> 1. 试着调小一点max_seq_len
> 2. 请问显存大小是多少呢，如果不够的话可以放在AI Studio上运行，显存16G
> 3. 试着跑一下ernie 自带的例程脚本，排查一下是机器问题还是代码问题

另外我直接跑https://aistudio.baidu.com/aistudio/projectdetail/515168这个连接中的教程代码也会出现同样的问题，请问这是因为我的机器不行吗？

**Comment by Meiyim** [comment]
8G显存应该足以运行大部分的demo；
考虑同一时期有其他进程占用显卡；
另外设置环境变量的时机，要放在`import paddle`之前才能管用；或者在启动脚本的时候加入`export FLAGS_fraction_of_gpu_memory_to_use=1.0`
另外请用最新的paddle版本(1.8+)；

**Comment by Firework471** [comment]
> 8G显存应该足以运行大部分的demo；
> 考虑同一时期有其他进程占用显卡；
> 另外设置环境变量的时机，要放在`import paddle`之前才能管用；或者在启动脚本的时候加入`export FLAGS_fraction_of_gpu_memory_to_use=1.0`
> 另外请用最新的paddle版本(1.8+)；

您好，谢谢您的建议。
我用的paddle版本是1.8.1
也把环境变量设置放在了import paddle之前，但还是出现了同样的问题。以下是我的代码，基本上是按照demo写的，只进行了少量的修改，代码中的BATCH和
MAX_SEQLEN我即使调成1和30仍然出现如下的报错信息：

```
Out of memory error on GPU 0. Cannot allocate 4.000244MB memory on GPU 0, available memory is only 3.349999MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 
```

这种情况下是只能换个机器试一试了吗？但是报错信息里面显示的“available memory is only 3.349999MB.”感觉显然是不现实的啊。
```
...
import os
os.environ['FLAGS_fraction_of_gpu_memory_to_use'] = "0.99"
os.environ["FLAGS_eager_delete_tensor_gb"] = "0"
...
BATCH=32
MAX_SEQLEN=100
LR=3e-5
EPOCH=10

D.guard().__enter__() # 为了让Paddle进入动态图模式，需要添加这一行在最前面

ernie = ErnieModelForSequenceClassification.from_pretrained('ernie-1.0', num_labels=3)
optimizer = F.optimizer.Adam(LR, parameter_list=ernie.parameters())
tokenizer = ErnieTokenizer.from_pretrained('ernie-1.0')

def make_data(path):
    data = []
    for i, l in enumerate(open(path, encoding='UTF-8')):
        if i == 0:
            continue
        l = l.strip().split('\t')
        text, label = l[3], int(l[1])
        text_id, _ = tokenizer.encode(text)
        text_id = text_id[:MAX_SEQLEN]
        text_id = np.pad(text_id, [0, MAX_SEQLEN-len(text_id)], mode='constant') 
        label_id = np.array(label+1, dtype='int64')
        data.append((text_id, label_id))
    return data
    
train_data = ...
test_data = ...

def get_batch_data(data, i):
    d = data[i*BATCH: (i + 1) * BATCH]
    feature, label = zip(*d)
    feature = np.stack(feature) 
    label = np.stack(list(label))
    feature = D.to_variable(feature) 
    label = D.to_variable(label)
    return feature, label

for i in range(EPOCH):

    np.random.shuffle(train_data) # 每个epoch都shuffle数据以获得最佳训练效果；
    #train
    for j in range(len(train_data) // BATCH):
        feature, label = get_batch_data(train_data, j)
        loss, _ = ernie(feature, labels=label) # ernie模型的返回值包含(loss, logits)；
        loss.backward()
        optimizer.minimize(loss)
        ernie.clear_gradients()
        if j % 10 == 0:
            print('train %d: loss %.5f' % (j, loss.numpy()))
        # evaluate
        if j % 100 == 0:
            all_pred, all_label = [], []
            with D.base._switch_tracer_mode_guard_(is_train=False):
                ernie.eval() 
                for j in range(len(test_data) // BATCH):
                    feature, label = get_batch_data(test_data, j)
                    loss, logits = ernie(feature, labels=label)
                    all_pred.extend(L.argmax(logits, -1).numpy())
                    all_label.extend(label.numpy())
                ernie.train()
            f1 = f1_score(all_label, all_pred, average='macro')
            acc = (np.array(all_label) == np.array(all_pred)).astype(np.float32).mean()
            print('acc %.5f' % acc)
```

**Comment by Meiyim** [comment]
> vailable memory is only 3.349999MB

对于这个warning不用太在意，它只是说执行到这一时刻时只剩3.34M显存；

从log里看你是在windows操作系统上运行的；这个代码库还没有在windows上测试过。
方便提供一下你的运行环境帮助我们收集一下信息么；
包括windows版本、cuda版本、显卡具体型号等。

另外除了减小`BATCH`, `MAX_SEQLEN` 以外还有一种办法是修改ernie_config.json文件的`num_hidden_layers`(在预训练模型包里) 从而减少transfomer的层数。

**Comment by Firework471** [comment]
> > vailable memory is only 3.349999MB
> 
> 对于这个warning不用太在意，它只是说执行到这一时刻时只剩3.34M显存；
> 
> 从log里看你是在windows操作系统上运行的；这个代码库还没有在windows上测试过。
> 方便提供一下你的运行环境帮助我们收集一下信息么；
> 包括windows版本、cuda版本、显卡具体型号等。
> 
> 另外除了减小`BATCH`, `MAX_SEQLEN` 以外还有一种办法是修改ernie_config.json文件的`num_hidden_layers`(在预训练模型包里) 从而减少transfomer的层数。

你好，我是python3.7，win10， paddle1.8.1，cuda10，GTX 1660 Ti

**Comment by Firework471** [comment]
我修改了ernie_config.json文件的num_hidden_layers，即便没有减小BATCH, MAX_SEQLEN也可以正常运行了，虽然我也不知道为什么，不过修改num_hidden_layers是可行的。
